import {
  ArrowRight,
  ArrowUpRight,
  BadgeCheck,
  Building2,
  CalendarDays,
  Camera,
  Check,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CircleCheckBig,
  CircleDashed,
  CircleDot,
  CircleEllipsis,
  CircleHelp,
  ClipboardCheck,
  ClipboardList,
  Clock3,
  CloudOff,
  Eye,
  EyeOff,
  FileText,
  FileUp,
  FolderOpen,
  Handshake,
  HardHat,
  History,
  House,
  Inbox,
  Info,
  KeyRound,
  Link2,
  LoaderCircle,
  Lock,
  LockKeyhole,
  LogOut,
  MailCheck,
  MapPin,
  MessageSquareText,
  Paperclip,
  Phone,
  Plus,
  Quote,
  RefreshCcw,
  Scale,
  ScrollText,
  Search,
  Send,
  Settings,
  Share2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Siren,
  Sparkles,
  TriangleAlert,
  Trash2,
  Upload,
  UserRound,
  Users,
  Video,
  WifiOff,
  Wrench,
  X,
  type LucideIcon
} from "lucide-react";

// Central icon registry: state metadata references icons by name so badges and
// timelines stay data-driven. Only these icons are bundled.
const REGISTRY: Record<string, LucideIcon> = {
  "arrow-right": ArrowRight,
  "arrow-up-right": ArrowUpRight,
  "badge-check": BadgeCheck,
  building: Building2,
  calendar: CalendarDays,
  camera: Camera,
  check: Check,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "circle-alert": CircleAlert,
  "circle-check": CircleCheck,
  "check-circle-2": CircleCheckBig,
  "circle-dashed": CircleDashed,
  "circle-dot": CircleDot,
  "circle-ellipsis": CircleEllipsis,
  "circle-help": CircleHelp,
  "clipboard-check": ClipboardCheck,
  "clipboard-list": ClipboardList,
  clock: Clock3,
  "cloud-off": CloudOff,
  eye: Eye,
  "eye-off": EyeOff,
  "file-text": FileText,
  "file-up": FileUp,
  folder: FolderOpen,
  handshake: Handshake,
  "hard-hat": HardHat,
  history: History,
  house: House,
  inbox: Inbox,
  info: Info,
  "key-round": KeyRound,
  link: Link2,
  "loader-circle": LoaderCircle,
  lock: Lock,
  "lock-keyhole": LockKeyhole,
  logout: LogOut,
  "mail-check": MailCheck,
  "map-pin": MapPin,
  message: MessageSquareText,
  paperclip: Paperclip,
  phone: Phone,
  plus: Plus,
  quote: Quote,
  refresh: RefreshCcw,
  scale: Scale,
  "scroll-text": ScrollText,
  search: Search,
  send: Send,
  settings: Settings,
  share: Share2,
  shield: Shield,
  "shield-alert": ShieldAlert,
  "shield-check": ShieldCheck,
  siren: Siren,
  sparkles: Sparkles,
  "triangle-alert": TriangleAlert,
  trash: Trash2,
  upload: Upload,
  user: UserRound,
  users: Users,
  video: Video,
  "wifi-off": WifiOff,
  wrench: Wrench,
  x: X
};

export function Icon({
  name,
  className,
  strokeWidth = 2
}: {
  name: string;
  className?: string;
  strokeWidth?: number;
}) {
  const Cmp = REGISTRY[name] || CircleHelp;
  return <Cmp className={className} strokeWidth={strokeWidth} aria-hidden="true" />;
}
